#
# Contains the full stack of the RTB4FREe stack (not including elk))
# Does contain zookeeper and kafka, postgres and minio
#
version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
     - "2181:2181"

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    # restart: always
    depends_on:
      - zookeeper

networks:
 rtb_net:
   external: true
