#
# Contains the full stack of the RTB4FREe stack (not including elk))
# Does contain zookeeper and kafka, postgres and minio
#
version: "3"

services:   
  bidder:
    image: jacamars/newbidder
    environment:
      BROKERLIST: "kafka:9092"
      EXTERNAL: "http://localhost:8080"
      JDBC: "jdbc:postgresql://sqldb/postgres?user=postgres&password=postgres"
      S3BUCKET: ""
      S3REGION: "us-east-1"
      S3ENDPOINT: "http://minio:9000"
      AWSACCESSKEY: "FvFIzKstCFg0N1MV"
      AWSSECRETKEY: "PUSrfylCENEOQBU6OYSTuUDS0c6Vvsmf"
      GOOGLE_EKEY: ""
      GOOGLE_IKEY: ""
      OPENX_EKEY: ""
      OPENX_IKEY: ""
      ADX_EKEY:   ""
      ADX_IKEY:   ""
    #volumes:
    #  - /payday.json:./Campaigns/payday.json
    ports:
      - "8080:8080"
      - "8155:8155"
      - "5701:5701"
      - "7379:7379"
    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh sqldb:5432 -t 120 && ./wait-for-it.sh minio:9000 -t 120 && ./rtb4free s3://rtb4free-big-data/config/payday.json"

networks:
 rtb_net:
   external: true