#
# Contains the full stack of the RTB4FREe stack (not including crosstalk, elk, mysql or campaign manager)
# Does contain zookeeper and kafka.
#
version: "3"

services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      # - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - /Users/chendan/project/adx/Newbidder/tmp/s3:/data
    command: server /data --console-address ":9090"


networks:
 rtb_net:
   external: true
